# pod-with-cpu-limits.yml

apiVersion: v1
kind: Pod
metadata:
  name: nnappone
  namespace: learning
  labels:
   app: nnappone
spec:
  containers:
    - name: networknuts-app
      image: lovelearnlinux/webserver:v1
      resources:
        limits:
          cpu: "1"
        requests:
          cpu: "0.5"

#
# Pod will start with 0.5 cpu share and can 
# go upto 1 cpu. Well within the permissible
# limits.
#
# create namespace learning -
# kubectl create namespace learning
#
# run the pod
# kubectl create -f pod-with-cpu-limits.yml
#
# check the pod
# kubectl get pods
#
# get details about pod
# kubectl describe pod/nnappone --namespace=learning
#
# delete pod
# kubectl delete pod/nnappone --namespace=learning
#
