# pod-simple-qos-burstable.yml
#
apiVersion: v1
kind: Pod
metadata:
  name: nnappone
  namespace: learning
  labels:
   app: nnappone
spec:
  containers:
    - name: networknuts-app
      image: lovelearnlinux/webserver:v1
      resources:
        limits:
          memory: "250Mi"
          cpu: "400m"
        requests:
          memory: "250Mi"
          cpu: "400m"
#
# Creating a simple pod. Which has apache
# configured inside it. There are memory & cpu 
# restrictions. But both are same so kubernetes 
# cluster will guarantee that much of 
# resources to the pod, before running it on any node.
#
# QoS = Guaranteed
#
# create namespace learning -
# kubectl create namespace learning
#
# run the pod
# kubectl create -f pod-simple-qos-guaranteed.yml
#
# check the pod
# kubectl get pods --namespace=learning
#
# get details about pod
# kubectl describe pod/nnappone --namespace=learning
# 
# Check the "QoS Class" value. 
#
# delete pod
# kubectl delete pod/nnappone --namespace=learning
#
