apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
 
 # expose this deployment with a service name "my-nginx-web-svc", which will send the request to port 80
 # of the containers
 # you can use - kubectl expose deployment .... 
 
